version: "3.8"

networks:
  front_nw:
  db_nw:

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: "none"
      o: bind
      device: "/Users/nerium/documents/programming/42/inception/inception_gh/volumes/mariadb"

  wp_vol:
    driver: local
    driver_opts:
      type: "none"
      o: bind
      device: "/Users/nerium/documents/programming/42/inception/inception_gh/volumes/wordpress"

services:
  mariadb:
    container_name: mariadb_container
    build: ./requirements/mariadb
    networks:
      - db_nw
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
    restart: always

  wordpress:
    container_name: wordpress_container
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    networks:
      - front_nw
      - db_nw
    volumes:
      - wp_vol:/var/www/html/wordpress
    env_file:
      - .env
    expose:
      - "9000"
    restart: always

  nginx:
    container_name: nginx_container
    depends_on:
      - wordpress
    build: ./requirements/nginx
    networks:
      - front_nw
    volumes:
      - wp_vol:/var/www/html/wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
