#!/bin/sh

/etc/init.d/mysql start
mysql -e "CREATE DATABASE IF NOT EXISTS ${WP_DB_NAME};"
# mysql -e "CREATE USER ${MYSQL_ROOT_USER}@${DOMAIN_NAME} IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}'"
mysql -e "CREATE USER ${MYSQL_USER}@${DOMAIN_NAME} IDENTIFIED BY '${MYSQL_PASSWORD}';"
# mysql -e "GRANT SUPER ON *.* TO '${MYSQL_ROOT_USER}'@'${DOMAIN_NAME}'"
mysql -e "GRANT ALL ON ${WP_DB_NAME}.* TO ${MYSQL_USER}@${DOMAIN_NAME};"
mysql -e "FLUSH PRIVILEGES"